//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FexDwnl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FexDwnl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fex Downloader.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unable to set culture to [{0}].
        /// </summary>
        internal static string ErrUnableToSetCultureToFmt {
            get {
                return ResourceManager.GetString("ErrUnableToSetCultureToFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;(empty)&quot;.
        /// </summary>
        internal static string LPfRgxEmpty {
            get {
                return ResourceManager.GetString("LPfRgxEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID REGEX!.
        /// </summary>
        internal static string LPfRgxInvalid {
            get {
                return ResourceManager.GetString("LPfRgxInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MATCH!.
        /// </summary>
        internal static string LPfRgxMatch {
            get {
                return ResourceManager.GetString("LPfRgxMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No match..
        /// </summary>
        internal static string LPfRgxNoMatch {
            get {
                return ResourceManager.GetString("LPfRgxNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No item selected.
        /// </summary>
        internal static string LPfStateNoItemSelected {
            get {
                return ResourceManager.GetString("LPfStateNoItemSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rule matches, Downloads folder will be used instead..
        /// </summary>
        internal static string LPfStateUUseDownloadsFolder {
            get {
                return ResourceManager.GetString("LPfStateUUseDownloadsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download complete.
        /// </summary>
        internal static string LStateDwnlComplete {
            get {
                return ResourceManager.GetString("LStateDwnlComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching....
        /// </summary>
        internal static string LStateFetching {
            get {
                return ResourceManager.GetString("LStateFetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping {0}: file already downloaded..
        /// </summary>
        internal static string LStateSkipSelectorFmt {
            get {
                return ResourceManager.GetString("LStateSkipSelectorFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping {0}: no regex match..
        /// </summary>
        internal static string LStateSkipSelectorNoMatchFmt {
            get {
                return ResourceManager.GetString("LStateSkipSelectorNoMatchFmt", resourceCulture);
            }
        }
    }
}
